### ISSUE TITLE
Invalid casting in backend

### ISSUE THREAD

**Issue by wxzh** [hkuplg/fcore#92]
The example

``` haskell
data P [A,B] = P A B;
let fst[A,B] (pair: P[B,A]): B =
    case pair of
      P x y -> x;
fst[Char,Int] (P[Int, Char] 1 'a')
```

produces the following error:

```
Pair using [Naive]
Compiling to Java source code ( ./Pair.java )
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Character
    at Pair.apply(Pair.java:56)
    at Pair.main(Pair.java:61)
```

**Comment by xnning** [comment]
I think data type is innocent here. 

code like this

```
let fst[A,B] (x:A) (y:B): B =
    y;
fst[Char,Int] 'a' 1
```

can not work.

```
Compiling to Java source code ( examples\Simple.java )
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer canno
t be cast to java.lang.Character
        at Simple.apply(Simple.java:33)
        at Simple.main(Simple.java:38)
```

the compiler got the return type wrong. This is the same error reason for above data type code.

**Comment by wxzh** [comment]
@xnning Thanks for generalising it :)
